# Tested: 2024/08/05
# by Kasper Arfman
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildozer dependencies
        run: |
          # sudo apt update
          # sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev automake
          # pip install --user --upgrade Cython virtualenv
          # pip install --user --upgrade buildozer
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          python -m venv venv
          source venv/bin/activate
          pip3 install --upgrade Cython==0.29.33 virtualenv
          sudo apt install build-essential git unp python3-pip python3-setuptools python3.12-venv
          python -m venv venv
          source venv/bin/activate
          pip install setuptools
          pip install buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      - name: Build the apk using buildozer
        run: |
          # export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          # sudo update-java-alternatives --set ${JAVA_HOME}
          # export PATH=$JAVA_HOME/bin:$PATH
          # yes | buildozer -v android debug
          source venv/bin/activate
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
